version: 0.2

env:
  variables:
    S3_BUCKET: "pdf-app-aws"
    APP_NAME: "PDFEditorPro"
  
  compute-type: BUILD_GENERAL1_MEDIUM  # More RAM for Android build

phases:
  install:
    runtime-versions:
      python: 3.10
    
    commands:
      - echo "=== INSTALLING DEPENDENCIES ==="
      - apt-get update -y
      - apt-get install -y \
          awscli \
          python3-pip \
          python3-venv \
          git \
          wget \
          curl \
          unzip \
          zip \
          openjdk-17-jdk \
          libssl-dev \
          libffi-dev \
          libsqlite3-dev \
          libjpeg-dev \
          zlib1g-dev

  pre_build:
    commands:
      - echo "=== SETTING UP BUILD ENVIRONMENT ==="
      - pip3 install --upgrade pip setuptools wheel
      - pip3 install buildozer cython virtualenv kivy
      
      # Install Android SDK
      - |
        echo "Setting up Android SDK..."
        mkdir -p /root/.android-sdk
        cd /root/.android-sdk
        
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -q commandlinetools-linux-9477386_latest.zip
        mkdir -p cmdline-tools/latest
        mv cmdline-tools/bin/* cmdline-tools/latest/
        
        export ANDROID_HOME=/root/.android-sdk
        export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest
        
        # Accept licenses
        yes | sdkmanager --licenses > /dev/null 2>&1 || true
      
      # Check for required files
      - |
        if [ ! -f main.py ]; then
          echo "ERROR: main.py not found!"
          exit 1
        fi
        
        if [ ! -f buildozer.spec ]; then
          echo "ERROR: buildozer.spec not found!"
          exit 1
        fi

  build:
    commands:
      - echo "=== BUILDING ANDROID APK ==="
      - cd $CODEBUILD_SRC_DIR
      
      # Initialize Buildozer
      - buildozer init 2>/dev/null || true
      
      # Clean previous builds
      - rm -rf .buildozer/bin .buildozer/dist 2>/dev/null || true
      
      # Build the APK (with 45 minute timeout)
      - |
        echo "Starting APK build (this may take 30+ minutes)..."
        
        # Try to build with Buildozer
        if timeout 2700 buildozer -v android debug 2>&1 | tee build.log; then
          echo "✅ Build completed"
        else
          echo "⚠️ Build timed out or failed"
        fi
        
        # Check for APK
        if ls bin/*.apk 1> /dev/null 2>&1; then
          APK_FILE=$(ls bin/*.apk | head -1)
          echo "✅ APK found: $APK_FILE"
          echo "Size: $(du -h "$APK_FILE" | cut -f1)"
          cp "$APK_FILE" pdf-editor.apk
          
          # Validate APK
          if unzip -t pdf-editor.apk 2>/dev/null; then
            echo "✅ APK is valid ZIP file"
            
            # Check Android structure
            if unzip -l pdf-editor.apk 2>/dev/null | grep -q "AndroidManifest.xml"; then
              echo "✅ Contains AndroidManifest.xml"
            fi
          fi
        else
          echo "❌ No APK found in bin/"
          echo "Check build.log for errors"
          exit 1
        fi

  post_build:
    commands:
      - echo "=== DEPLOYING TO S3 ==="
      
      # Upload APK
      - |
        TIMESTAMP=$(date +%Y%m%d_%H%M%S)
        echo "Uploading APK to S3..."
        aws s3 cp pdf-editor.apk s3://$S3_BUCKET/ --acl public-read
        aws s3 cp pdf-editor.apk s3://$S3_BUCKET/pdf-editor-$TIMESTAMP.apk --acl public-read
      
      # Create download page
      - |
        echo "Creating download page..."
        APK_SIZE=$(du -h pdf-editor.apk | cut -f1)
        
        cat > index.html << HTML
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PDF Editor Pro - Download</title>
    <style>
        body { font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; }
        .header { text-align: center; padding: 30px 0; }
        .download-btn {
            display: block; width: 200px; margin: 20px auto; padding: 15px;
            background: #4CAF50; color: white; text-align: center;
            text-decoration: none; border-radius: 5px; font-size: 18px;
        }
        .info { background: #f5f5f5; padding: 15px; border-radius: 5px; margin: 20px 0; }
        .steps { margin: 30px 0; }
        .steps li { margin: 10px 0; }
    </style>
</head>
<body>
    <div class="header">
        <h1>📄 PDF Editor Pro</h1>
        <p>Edit, merge, and manage PDF files on Android</p>
    </div>
    
    <div class="info">
        <p><strong>Version:</strong> 1.0.0</p>
        <p><strong>Size:</strong> $APK_SIZE</p>
        <p><strong>Android:</strong> 5.0+ (API 21+)</p>
    </div>
    
    <a href="https://$S3_BUCKET.s3.amazonaws.com/pdf-editor.apk" 
       class="download-btn" 
       download="pdf-editor-pro.apk">
        ⬇️ Download APK
    </a>
    
    <div class="steps">
        <h3>Installation:</h3>
        <ol>
            <li>Tap Download button above</li>
            <li>Open Downloads folder on your phone</li>
            <li>Tap "pdf-editor-pro.apk"</li>
            <li>Allow "Install from unknown sources" if prompted</li>
            <li>Tap Install → Open</li>
        </ol>
    </div>
    
    <p style="text-align: center; color: #666; margin-top: 40px;">
        Built with AWS CodeBuild • Kivy • Python
    </p>
</body>
</html>
HTML
        
        aws s3 cp index.html s3://$S3_BUCKET/ --acl public-read
        aws s3 website s3://$S3_BUCKET/ --index-document index.html
        
        echo "✅ Deployment complete!"
        echo "🌐 Website: https://$S3_BUCKET.s3.amazonaws.com"
        echo "📱 Direct APK: https://$S3_BUCKET.s3.amazonaws.com/pdf-editor.apk"

artifacts:
  files:
    - 'pdf-editor.apk'
    - 'index.html'
    - 'build.log'
  base-directory: '.'
