version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - apt-get update
      - apt-get install -y openjdk-17-jdk unzip zip git
      - pip install --upgrade pip
      - pip install buildozer cython

  pre_build:
    commands:
      - buildozer android debug

  build:
    commands:
      - echo "APK build completed"

artifacts:
  files:
    - bin/*.apk
